import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'mr';

export interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string, defaultText?: string) => string;
}

const STORAGE_KEY = 'varinet_language_preference';

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Brand & App
    'app.name': 'VARI-Net',
    'app.subtitle': 'Command Portal',
    'app.tagline': 'CONNECT • PREDICT • RECOMMEND • PREVENT',
    'app.location': 'Pandharpur Wari',
    
    // Roles
    'role.police': 'Police Command',
    'role.police.desc': 'Incident triage, AI intervention approval & GIS command',
    'role.volunteer': 'Volunteer Field Ops',
    'role.volunteer.desc': 'Ground dispatch tasks, crowd guidance & incident reporting',
    'role.pilgrim': 'Pilgrim App',
    'role.pilgrim.desc': 'Live safe route navigation, water points & emergency SOS',
    'role.temple': 'Temple Authority',
    'role.temple.desc': 'Sanctum throughput, queue holding & VIP protocol',
    
    // Navigation & Header
    'nav.activeStation': 'Active Station',
    'nav.unauthenticated': 'Pilgrim Public Access',
    'nav.offline': 'Offline (Cached Map)',
    'nav.lowNetwork': 'Low Network (Cached)',
    'nav.online': 'Online Sync',
    'nav.liveClock': 'IST',
    'nav.soundOn': 'Alert sirens enabled',
    'nav.soundOff': 'Alert sirens muted',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings & Preferences',
    'nav.logout': 'Logout & End Session',
    'nav.switchRole': 'Switch Role',
    'nav.quickPilgrim': 'Direct Pilgrim View',
    
    // Pilgrim App
    'pilgrim.emergencySos': 'EMERGENCY SOS',
    'pilgrim.safetyStatus': 'Current Safety Status',
    'pilgrim.safeTitle': 'Sector C (Palkhi Marg) is Safe & Moving',
    'pilgrim.safeDesc': 'Crowd movement is steady. Average flow rate: 64 pilgrims/min. Nearest shaded rest tent is 180m ahead.',
    'pilgrim.warningTitle': 'Caution: Heavy Crowd Congestion Ahead',
    'pilgrim.warningDesc': 'Crowd density is high near Shivaji Chowk. AI recommends taking Bypass 2 shaded corridor.',
    'pilgrim.criticalTitle': 'High Risk Alert: Use Emergency Bypass',
    'pilgrim.criticalDesc': 'Critical bottleneck detected at Main Palkhi Marg. Turn right towards Shaded Corridor 2.',
    'pilgrim.nearestWater': 'Nearest Water Point',
    'pilgrim.nearestMedical': 'Nearest Medical Aid',
    'pilgrim.templeQueue': 'Temple Darshan Queue',
    'pilgrim.waitTime': 'Estimated Wait',
    'pilgrim.minutes': 'mins',
    'pilgrim.meters': 'meters away',
    'pilgrim.recommendedSafeRoute': 'AI Recommended Safe Corridor (Bypass 2)',
    'pilgrim.recommendedBadge': 'Recommended • Less Crowded',
    'pilgrim.mainCorridor': 'Main Palkhi Marg (Heavy Crowd)',
    'pilgrim.mapLayers': 'Map Layers',
    'pilgrim.routes': 'Routes',
    'pilgrim.facilities': 'Facilities',
    'pilgrim.showAll': 'Show All',
    'pilgrim.walkingRoute': 'Walking Spine Routes',
    'pilgrim.safeCorridor': 'AI Safe Corridor (Bypass 2)',
    'pilgrim.waterPoints': 'Drinking Water Points',
    'pilgrim.medicalCamps': 'Medical & ICU Camps',
    'pilgrim.toilets': 'Toilets & Sanitation',
    'pilgrim.policeBooths': 'Police / Help Centers',
    'pilgrim.templeDarshan': 'Temple / Darshan',
    'pilgrim.foodPrasad': 'Food / Prasadalaya',
    'pilgrim.otherServices': 'Other Important Services',
    'pilgrim.allServices': 'All Services',
    'pilgrim.searchServices': 'Search nearby services...',
    'pilgrim.nearbyRadius': 'Nearby',
    'pilgrim.noServicesFound': 'No nearby services found',
    'pilgrim.noServicesFoundDesc': 'Try another category or increase your search radius.',
    'pilgrim.viewMore': 'View More',
    'pilgrim.showLess': 'Show Less',
    'pilgrim.resetFilters': 'Reset Filters',
    'pilgrim.showingServices': 'Showing',
    'pilgrim.shelters': 'Rest Shelters & Food',
    'pilgrim.riskZones': 'Safety & Crowd Risk Zones',

    // Temple Dashboard
    'temple.title': 'Temple Sanctum & Darshan Queue Operations',
    'temple.activeZone': 'Active Operational Zone',
    'temple.darshanQueue': 'Darshan Queue',
    'temple.avgWait': 'Avg Wait Time',
    'temple.throughput': 'Throughput',
    'temple.mandapCapacity': 'Holding Mandap Capacity',
    'temple.mandapHeader': 'Holding Mandap Flow & Queue Control',
    'temple.sanctumPacing': 'Sanctum Discharge & Pacing Control',
    'temple.openReleaseGate': 'Open Release Gate',
    'temple.pauseGate': 'Pause Queue Gate',
    'temple.adjustPace': 'Adjust Pacing',
    'temple.vipProtocol': 'VIP Protocol Override',
    'temple.flowRate': 'Discharge Rate',
    'temple.personsPerMin': 'persons/min',
    'temple.queueLength': 'Total Pilgrims in Queue',
    'temple.holdingArea': 'Mandap Capacity',
    'temple.gateStatus': 'Gate State',
    'temple.activeInterventions': 'Active Directives',
    'temple.emergencyBuffer': 'Buffer Capacity',

    // Police Dashboard
    'police.title': 'Police Command & Incident Response Center',
    'police.crowdTelemetry': 'Ground Crowd Telemetry',
    'police.gisMap': 'Interactive GIS Operations Map',
    'police.incidentTriage': 'Incident Triage & Field Unit Status',
    'police.aiDecisionTitle': 'AI Predictive Decision Engine',
    'police.dispatchUnits': 'Dispatch Response Units',
    'police.activeIncidents': 'Active Incidents',
    'police.resolvedIncidents': 'Resolved Incidents',
    'police.totalIncidents': 'Total Field Alerts',
    'police.density': 'Crowd Density',
    'police.surgeRisk': 'Surge Risk Level',
    'police.hotspots': 'Active Hotspots',
    'police.filterAll': 'All Priorities',
    'police.filterCritical': 'Critical Only',
    'police.filterHigh': 'High Priority',
    'police.viewOnMap': 'Locate on Map',
    'police.assignUnit': 'Assign Units',
    'police.markResolved': 'Mark Resolved',

    // Volunteer Dashboard
    'volunteer.title': 'Volunteer Field Ops & Task Dispatch',
    'volunteer.quickReport': 'Quick Field Report (10s)',
    'volunteer.assignedTasks': 'My Assigned Tasks',
    'volunteer.nearbyFacilities': 'Nearby Relief Facilities',
    'volunteer.taskInProgress': 'In Progress',
    'volunteer.markComplete': 'Mark Completed',
    'volunteer.acceptTask': 'Accept Task',
    'volunteer.activeVolunteers': 'Active Personnel',
    'volunteer.completedTasks': 'Tasks Completed',
    'volunteer.distributeWater': 'Distribute Water & ORS',
    'volunteer.waterPointsStatus': 'Water Points Monitored',
    'volunteer.medicalAssists': 'Medical Assists Rendered',
    'volunteer.activeZoneNotice': 'Active Assigned Sector: Sector C (Palkhi Marg)',

    // Decision Card
    'decision.title': 'AI Predictive Crowd Safety Intervention',
    'decision.confidence': 'AI Confidence',
    'decision.approve': 'Approve & Execute',
    'decision.approved': 'Intervention Approved',
    'decision.dismiss': 'Dismiss Recommendation',
    'decision.impactPreview': 'Predicted Telemetry Impact',
    'decision.affectedZones': 'Target Reroute Corridors',
    'decision.corridors': 'Corridor Densities',
    'decision.timeline': 'Timeline Impact',
    'decision.beforeAfter': 'Before vs After AI Intervention',

    // Facility & Incidents
    'facility.capacity': 'Capacity',
    'facility.route': 'Get Route',
    'facility.waterStation': 'Drinking Water Point',
    'facility.medicalCamp': 'Medical Camp',
    'facility.policeBooth': 'Police Help Post',
    'facility.sanitation': 'Sanitation Block',
    'facility.shelter': 'Rest Shelter',
    'facility.prasadCamp': 'Maha-Prasad Camp',
    
    'incident.acknowledge': 'Acknowledge',
    'incident.assign': 'Assign Units',
    'incident.resolve': 'Close & Resolve',
    'incident.reportedBy': 'Reported by',
    'incident.photo': 'Photo attached',
    'incident.voice': 'Voice note attached',
    
    // Weather & Microclimate
    'weather.title': 'Zone Microclimate Radar',
    'weather.temp': 'Temperature',
    'weather.humidity': 'Humidity',
    'weather.wind': 'Wind Speed',
    'weather.heatRisk': 'Heat Risk',
    'weather.dehydration': 'Dehydration Warning',
    'weather.dehydrationDesc': 'ORS and hydration recommended across this corridor.',

    // Map Layers
    'map.layers': 'GIS Map Layers',
    'map.quickFilter.title': 'GIS Layer Quick Filters',
    'map.quickFilter.water': 'Water Points',
    'map.quickFilter.medical': 'Medical Posts',
    'map.quickFilter.police': 'Police Posts',
    'map.quickFilter.food': 'Food Camps',
    'map.quickFilter.safeCorridor': 'AI Safe Corridor',
    'map.quickFilter.walkingRoutes': 'Walking Spine Routes',
    'map.palkhiRoutes': 'Palkhi Spine Routes',
    'map.altRoutes': 'Alternate Corridors',
    'map.waterPoints': 'Water Points & RO',
    'map.medicalCamps': 'Medical Camps & ICU',
    'map.policeBooths': 'Police Booths & QRT',
    'map.toilets': 'Sanitation Blocks',
    'map.shelters': 'Shelters & Annachhatra',
    'map.parking': 'Depot & Parking Hubs',
    'map.crowdDensity': 'Live Crowd Density',
    'map.incidents': 'Active Incidents',
    'map.volunteers': 'Volunteer Personnel',
    'map.policeUnits': 'Police Patrols',
    'map.ambulances': 'Ambulance Units',
    'map.weatherOverlay': 'Microclimate Weather',
    'map.riskZones': 'AI Risk Polygons',
    'map.safeRoutes': 'AI Safe Corridors',
    'map.predictedCongestion': 'Predicted Congestion (1hr)',
    'map.recommendedInterventions': 'Intervention Zones',

    // Auth & Login
    'auth.welcome': 'Welcome to VARI-Net Command',
    'auth.heroDesc': 'Unified crowd safety, microclimate telemetry, real-time AI rerouting, and multi-agency coordination for the Pandharpur Wari pilgrimage.',
    'auth.fullName': 'Full Name',
    'auth.userId': 'Badge Number / Officer ID',
    'auth.pin': 'Password / Security PIN',
    'auth.signIn': 'Authorize & Enter Command',
    'auth.selectRole': 'Select Operational Role',
    'auth.guestPilgrim': 'Direct Pilgrim Access (No Login Required)',
    'auth.securityNotice': 'Role-Based Access Control • MVP Secure Session',

    // Notifications & Stream
    'notif.title': 'Command Alert Stream',
    'notif.all': 'All Alerts',
    'notif.critical': 'Critical & High',
    'notif.ops': 'Operations',
    'notif.public': 'Public & Pilgrim',
    'notif.empty': 'No active alerts. Ground operations nominal.',
    'notif.dismiss': 'Dismiss',
    'notif.clearAll': 'Clear All',
    'notif.viewAction': 'View Action',
    'notif.toast': 'Real-Time Alert',

    // Expandable Action Bar Keys
    'actionBar.crowdDensityHeatmaps': 'Crowd Density Heatmaps',
    'actionBar.activeInterventionsDiversions': 'Active Interventions & Diversions',
    'actionBar.incidentTriageFieldUnits': 'Incident Triage & Field Units',
    'actionBar.alternateCorridors': 'Alternate Corridors',
    'actionBar.interactiveGisMap': 'Interactive GIS Map',
    'actionBar.safeRouteNav': 'Safe Route Navigation',
    'actionBar.nearbyServices': 'Nearby Services (Water / Toilets / Medical)',
    'actionBar.sectorWaitTimes': 'Waiting Time at Different Sectors',
    'actionBar.emergencySos': 'Emergency SOS',
    'actionBar.queueControls': 'Queue Management Controls',
    'actionBar.darshanQueue': 'Darshan Queue',
    'actionBar.assignedTasks': 'Assigned Tasks',
    'actionBar.facilities': 'Facilities',
    'actionBar.quickIncidentReport': 'Quick Incident Report',
    
    // Settings & Profile Modal
    'settings.title': 'Universal Profile & Settings',
    'settings.profileTitle': 'Active User Profile',
    'settings.role': 'Operational Role',
    'settings.id': 'Station ID / Badge',
    'settings.status': 'Live Operational Session',
    'settings.languageTitle': 'Language Preferences',
    'settings.languageOverride': 'Language Override',
    'settings.multiAgentView': 'Multi-Agent View Mode',
    'settings.lowBandwidth': 'Low-Bandwidth Mode',
    'settings.standardView': 'Standard View',
    'settings.commandView': 'Advanced Command View',
    'settings.optionsTitle': 'General & Alert Options',
    'settings.audioAlerts': 'Audio Siren & Chimes',
    'settings.audioAlertsDesc': 'Play high-priority audible siren when critical incidents are detected',
    'settings.toastAlerts': 'Actionable Screen Toasts',
    'settings.toastAlertsDesc': 'Overlay real-time pop-up notification cards for critical crowd risks',
    'settings.vibration': 'Haptic Vibration Warnings',
    'settings.vibrationDesc': 'Vibrate device upon entering high-risk or congested pilgrim zones',
    'settings.offlineSync': 'Offline Cache Auto-Sync',
    'settings.offlineSyncDesc': 'Periodically synchronize route maps and facility locations in background',
    'settings.save': 'Save Preferences',
    'settings.close': 'Close',

    // Common Buttons & Badges
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.details': 'Details',
    'common.hide': 'Hide',
    'common.active': 'Active',
    'common.resolved': 'Resolved',
    'common.critical': 'Critical',
    'common.high': 'High',
    'common.medium': 'Medium',
    'common.low': 'Low',
    'common.syncCache': 'Sync Cache',
    'common.instantPilgrimAccess': 'Direct Pilgrim Access (No Login Required)',
    'common.operationalStaff': 'Operational Staff Sign In',
  },
  
  hi: {
    // Brand & App
    'app.name': 'वारी-नेट (VARI-Net)',
    'app.subtitle': 'कमांड पोर्टल',
    'app.tagline': 'जोड़ें • अनुमान लगाएं • सुझाव दें • सुरक्षित रखें',
    'app.location': 'पंढरपूर वारी',
    
    // Roles
    'role.police': 'पुलिस कमांड',
    'role.police.desc': 'घटना नियंत्रण, एआई हस्तक्षेप अनुमोदन व जीआईएस कमांड',
    'role.volunteer': 'स्वयंसेवक फील्ड ऑप्स',
    'role.volunteer.desc': 'ग्राउंड कार्य, भीड़ मार्गदर्शन व त्वरित रिपोर्टिंग',
    'role.pilgrim': 'वारकरी / तीर्थयात्री ऐप',
    'role.pilgrim.desc': 'लाइव सुरक्षित मार्ग, जल केंद्र व आपातकालीन एसओएस',
    'role.temple': 'मंदिर प्रशासन',
    'role.temple.desc': 'गर्भगृह प्रवाह, कतार प्रबंधन व दर्शन नियंत्रण',
    
    // Navigation & Header
    'nav.activeStation': 'सक्रिय स्टेशन',
    'nav.unauthenticated': 'वारकरी सार्वजनिक पहुंच',
    'nav.offline': 'ऑफलाइन (कैश मैप)',
    'nav.lowNetwork': 'कम नेटवर्क (कैश सक्रिय)',
    'nav.online': 'लाइव सिंक',
    'nav.liveClock': 'भारतीय समय',
    'nav.soundOn': 'ध्वनि अलर्ट चालू',
    'nav.soundOff': 'ध्वनि अलर्ट म्यूट',
    'nav.notifications': 'सूचनाएं',
    'nav.settings': 'सेटिंग्स व प्रोफ़ाइल',
    'nav.logout': 'लॉगआउट व सत्र समाप्त',
    'nav.switchRole': 'भूमिका बदलें',
    'nav.quickPilgrim': 'सीधा वारकरी दृश्य',
    
    // Pilgrim App
    'pilgrim.emergencySos': '🚨 आपातकालीन SOS',
    'pilgrim.safetyStatus': 'वर्तमान सुरक्षा स्थिति',
    'pilgrim.safeTitle': 'सेक्टर सी (पालखी मार्ग) सुरक्षित व सुचारु है',
    'pilgrim.safeDesc': 'भीड़ की आवाजाही सामान्य है। गति: ६४ वारकरी/मिनट। १८० मीटर आगे छायादार विश्राम शिविर है।',
    'pilgrim.warningTitle': 'सावधानी: आगे शिवाजी चौक पर भारी भीड़ है',
    'pilgrim.warningDesc': 'पालखी मार्ग पर भीड़ का दबाव अधिक है। एआई बायपास २ छायादार मार्ग लेने की सलाह देता है।',
    'pilgrim.criticalTitle': 'उच्च जोखिम चेतावनी: आपातकालीन बायपास लें',
    'pilgrim.criticalDesc': 'मुख्य मार्ग पर अत्यधिक भीड़। कृपया दाईं ओर मुड़कर छायादार कॉरिडोर २ का उपयोग करें।',
    'pilgrim.nearestWater': 'निकटतम पेयजल केंद्र',
    'pilgrim.nearestMedical': 'निकटतम चिकित्सा सहायता',
    'pilgrim.templeQueue': 'मंदिर दर्शन कतार',
    'pilgrim.waitTime': 'अनुमानित समय',
    'pilgrim.minutes': 'मिनट',
    'pilgrim.meters': 'मीटर दूर',
    'pilgrim.recommendedSafeRoute': 'एआई सुरक्षित मार्ग (बायपास २ छायादार मार्ग)',
    'pilgrim.recommendedBadge': 'सुझाया गया • कम भीड़',
    'pilgrim.mainCorridor': 'मुख्य पालखी मार्ग (भारी भीड़)',
    'pilgrim.mapLayers': 'मैप लेयर्स',
    'pilgrim.routes': 'मार्ग',
    'pilgrim.facilities': 'सुविधाएं',
    'pilgrim.showAll': 'सभी दिखाएं',
    'pilgrim.walkingRoute': 'पैदल पालखी मार्ग',
    'pilgrim.safeCorridor': 'एआई सुरक्षित कॉरिडोर (बायपास २)',
    'pilgrim.waterPoints': 'पीने का पानी (जल केंद्र)',
    'pilgrim.medicalCamps': 'चिकित्सा व ICU शिविर',
    'pilgrim.toilets': 'शौचालय व स्वच्छता',
    'pilgrim.policeBooths': 'पुलिस व सहायता केंद्र',
    'pilgrim.templeDarshan': 'मंदिर व दर्शन',
    'pilgrim.foodPrasad': 'महाप्रसाद व अन्नछत्र',
    'pilgrim.otherServices': 'अन्य महत्वपूर्ण सेवाएं',
    'pilgrim.allServices': 'सभी सेवाएं',
    'pilgrim.searchServices': 'आसपास की सेवाएं खोजें...',
    'pilgrim.nearbyRadius': 'दूरी सीमा',
    'pilgrim.noServicesFound': 'कोई नजदीकी सेवा नहीं मिली',
    'pilgrim.noServicesFoundDesc': 'कृपया दूसरी श्रेणी चुनें या खोज का दायरा बढ़ाएं।',
    'pilgrim.viewMore': 'अधिक देखें',
    'pilgrim.showLess': 'कम देखें',
    'pilgrim.resetFilters': 'फ़िल्टर रीसेट करें',
    'pilgrim.showingServices': 'दिखा रहे हैं',
    'pilgrim.shelters': 'विश्राम शेड व अन्नछत्र',
    'pilgrim.riskZones': 'भीड़ सुरक्षा व जोखिम क्षेत्र',

    // Temple Dashboard
    'temple.title': 'मंदिर गर्भगृह व दर्शन कतार प्रबंधन',
    'temple.activeZone': 'सक्रिय परिचालन क्षेत्र',
    'temple.darshanQueue': 'दर्शन कतार',
    'temple.avgWait': 'औसत प्रतीक्षा समय',
    'temple.throughput': 'दर्शन प्रवाह दर',
    'temple.mandapCapacity': 'दर्शन मंडप क्षमता',
    'temple.mandapHeader': 'दर्शन मंडप प्रवाह व कतार नियंत्रण',
    'temple.sanctumPacing': 'गर्भगृह निकास व गति नियंत्रण',
    'temple.openReleaseGate': 'प्रवेश द्वार खोलें',
    'temple.pauseGate': 'कतार द्वार रोकें',
    'temple.adjustPace': 'गति समायोजित करें',
    'temple.vipProtocol': 'वीआईपी प्रोटोकॉल',
    'temple.flowRate': 'निकास प्रवाह दर',
    'temple.personsPerMin': 'व्यक्ति/मिनट',
    'temple.queueLength': 'कतार में कुल वारकरी',
    'temple.holdingArea': 'मंडप क्षमता',
    'temple.gateStatus': 'गेट की स्थिति',
    'temple.activeInterventions': 'सक्रिय निर्देश',
    'temple.emergencyBuffer': 'बफर क्षमता',

    // Police Dashboard
    'police.title': 'पुलिस कमांड व त्वरित प्रतिक्रिया केंद्र',
    'police.crowdTelemetry': 'ग्राउंड भीड़ टेलीमेट्री',
    'police.gisMap': 'इंटरैक्टिव जीआईएस ऑपरेशन मैप',
    'police.incidentTriage': 'घटना निवारण व फील्ड यूनिट स्थिति',
    'police.aiDecisionTitle': 'एआई पूर्वानुमान व निर्णय प्रणाली',
    'police.dispatchUnits': 'प्रतिक्रिया दल रवाना करें',
    'police.activeIncidents': 'सक्रिय घटनाएं',
    'police.resolvedIncidents': 'हल हुई घटनाएं',
    'police.totalIncidents': 'कुल फील्ड अलर्ट',
    'police.density': 'भीड़ घनत्व',
    'police.surgeRisk': 'दबाव जोखिम स्तर',
    'police.hotspots': 'सक्रिय संवेदनशील क्षेत्र',
    'police.filterAll': 'सभी प्राथमिकताएं',
    'police.filterCritical': 'केवल अति-गंभीर',
    'police.filterHigh': 'उच्च प्राथमिकता',
    'police.viewOnMap': 'मानचित्र पर देखें',
    'police.assignUnit': 'यूनिट सौंपें',
    'police.markResolved': 'हल चिह्नित करें',

    // Volunteer Dashboard
    'volunteer.title': 'स्वयंसेवक फील्ड ऑप्स व कार्य प्रबंधन',
    'volunteer.quickReport': 'त्वरित फील्ड रिपोर्ट (१० सेकंड)',
    'volunteer.assignedTasks': 'मेरे सौंपे गए कार्य',
    'volunteer.nearbyFacilities': 'निकटवर्ती राहत सुविधाएं',
    'volunteer.taskInProgress': 'प्रगति पर है',
    'volunteer.markComplete': 'पूर्ण चिह्नित करें',
    'volunteer.acceptTask': 'कार्य स्वीकार करें',
    'volunteer.activeVolunteers': 'सक्रिय स्वयंसेवक',
    'volunteer.completedTasks': 'पूर्ण कार्य',
    'volunteer.distributeWater': 'जल व ओआरएस वितरण',
    'volunteer.waterPointsStatus': 'निगरानी किए गए जल केंद्र',
    'volunteer.medicalAssists': 'दी गई चिकित्सा सहायता',
    'volunteer.activeZoneNotice': 'सक्रिय आवंटित क्षेत्र: सेक्टर सी (पालखी मार्ग)',

    // Decision Card
    'decision.title': 'एआई अनुशंसित भीड़ सुरक्षा कार्रवाई',
    'decision.confidence': 'एआई सटीकता',
    'decision.approve': 'स्वीकृत करें व मार्ग बदलें',
    'decision.approved': 'कार्रवाई स्वीकृत व सक्रिय',
    'decision.dismiss': 'सिफारिश अस्वीकार करें',
    'decision.impactPreview': 'पूर्वानुमानित टेलीमेट्री प्रभाव',
    'decision.affectedZones': 'प्रभावित डायवर्जन गलियारे',
    'decision.corridors': 'गलियारा घनत्व',
    'decision.timeline': 'समय में कमी',
    'decision.beforeAfter': 'कार्रवाई से पहले बनाम बाद में',

    // Facility & Incidents
    'facility.capacity': 'क्षमता',
    'facility.route': 'मार्ग देखें',
    'facility.waterStation': 'पीने का पानी केंद्र',
    'facility.medicalCamp': 'चिकित्सा शिविर',
    'facility.policeBooth': 'पुलिस सहायता बूथ',
    'facility.sanitation': 'शौचालय ब्लॉक',
    'facility.shelter': 'विश्राम शेड',
    'facility.prasadCamp': 'महा-प्रसाद शिविर',
    
    'incident.acknowledge': 'स्वीकार करें',
    'incident.assign': 'यूनिट सौंपें',
    'incident.resolve': 'हल करें व बंद करें',
    'incident.reportedBy': 'द्वारा रिपोर्ट',
    'incident.photo': 'फोटो संलग्न',
    'incident.voice': 'वॉइस नोट संलग्न',
    
    // Weather & Microclimate
    'weather.title': 'क्षेत्र सूक्ष्म-जलवायु रडार',
    'weather.temp': 'तापमान',
    'weather.humidity': 'आर्द्रता',
    'weather.wind': 'हवा की गति',
    'weather.heatRisk': 'गर्मी का जोखिम',
    'weather.dehydration': 'निर्जलीकरण चेतावनी',
    'weather.dehydrationDesc': 'इस मार्ग पर ओआरएस व जल सेवन की सलाह दी जाती है।',

    // Map Layers
    'map.layers': 'जीआईएस मैप लेयर्स',
    'map.quickFilter.title': 'जीआईएस त्वरित फ़िल्टर',
    'map.quickFilter.water': 'पेयजल केंद्र',
    'map.quickFilter.medical': 'चिकित्सा केंद्र',
    'map.quickFilter.police': 'पुलिस सहायता केंद्र',
    'map.quickFilter.food': 'अन्नछत्र व भोजन',
    'map.quickFilter.safeCorridor': 'एआई सुरक्षित मार्ग',
    'map.quickFilter.walkingRoutes': 'पैदल पालखी मार्ग',
    'map.palkhiRoutes': 'पालखी मुख्य मार्ग',
    'map.altRoutes': 'वैकल्पिक गलियारे',
    'map.waterPoints': 'पेयजल केंद्र व आरओ',
    'map.medicalCamps': 'चिकित्सा केंद्र व आईसीयू',
    'map.policeBooths': 'पुलिस सहायता बूथ व क्यूआरटी',
    'map.toilets': 'शौचालय ब्लॉक',
    'map.shelters': 'विश्राम शेड व अन्नछत्र',
    'map.parking': 'डिपो व पार्किंग हब',
    'map.crowdDensity': 'लाइव भीड़ घनत्व',
    'map.incidents': 'सक्रिय घटनाएं',
    'map.volunteers': 'स्वयंसेवक दल',
    'map.policeUnits': 'पुलिस गश्ती दल',
    'map.ambulances': 'एम्बुलेंस यूनिट्स',
    'map.weatherOverlay': 'मौसम ओवरले',
    'map.riskZones': 'एआई जोखिम क्षेत्र',
    'map.safeRoutes': 'एआई सुरक्षित गलियारे',
    'map.predictedCongestion': 'पूर्वानुमानित भीड़ (१ घंटा)',
    'map.recommendedInterventions': 'हस्तक्षेप लक्ष्य क्षेत्र',

    // Auth & Login
    'auth.welcome': 'वारी-नेट कमांड में आपका स्वागत है',
    'auth.heroDesc': 'पंढरपूर वारी के लिए एकीकृत भीड़ सुरक्षा, सूक्ष्म-जलवायु टेलीमेट्री, रियल-टाइम एआई रूटिंग और बहु-एजेंसी समन्वय।',
    'auth.fullName': 'पूरा नाम',
    'auth.userId': 'बैज नंबर / अधिकारी आईडी',
    'auth.pin': 'पासवर्ड / सुरक्षा पिन',
    'auth.signIn': 'प्रवेश करें व कमांड शुरू करें',
    'auth.selectRole': 'परिचालन भूमिका चुनें',
    'auth.guestPilgrim': 'सीधा वारकरी प्रवेश (लॉगिन की आवश्यकता नहीं)',
    'auth.securityNotice': 'भूमिका आधारित सुरक्षा नियंत्रण • सुरक्षित सत्र',

    // Notifications & Stream
    'notif.title': 'कमांड अलर्ट स्ट्रीम',
    'notif.all': 'सभी अलर्ट',
    'notif.critical': 'अति-महत्वपूर्ण व उच्च',
    'notif.ops': 'फील्ड ऑपरेशन्स',
    'notif.public': 'वारकरी व जन सूचना',
    'notif.empty': 'कोई सक्रिय अलर्ट नहीं। सभी व्यवस्थाएं सामान्य हैं।',
    'notif.dismiss': 'हटाएं',
    'notif.clearAll': 'सभी साफ़ करें',
    'notif.viewAction': 'कार्रवाई देखें',
    'notif.toast': 'तत्काल अलर्ट',

    // Expandable Action Bar Keys
    'actionBar.crowdDensityHeatmaps': 'भीड़ घनत्व हीटमैप्स',
    'actionBar.activeInterventionsDiversions': 'सक्रिय हस्तक्षेप व डायवर्जन',
    'actionBar.incidentTriageFieldUnits': 'घटना ट्राइएज व फील्ड यूनिट्स',
    'actionBar.alternateCorridors': 'वैकल्पिक गलियारे',
    'actionBar.interactiveGisMap': 'इंटरैक्टिव GIS मैप',
    'actionBar.safeRouteNav': 'सुरक्षित मार्ग नेविगेशन',
    'actionBar.nearbyServices': 'निकटवर्ती सुविधाएं (जल / शौचालय)',
    'actionBar.sectorWaitTimes': 'विभिन्न सेक्टर प्रतीक्षा समय',
    'actionBar.emergencySos': 'आपातकालीन SOS',
    'actionBar.queueControls': 'कतार प्रबंधन नियंत्रण',
    'actionBar.darshanQueue': 'दर्शन कतार',
    'actionBar.assignedTasks': 'सौंपे गए कार्य',
    'actionBar.facilities': 'सुविधाएं',
    'actionBar.quickIncidentReport': 'त्वरित घटना रिपोर्ट',
    
    // Settings & Profile Modal
    'settings.title': 'सार्वभौमिक प्रोफ़ाइल व सेटिंग्स',
    'settings.profileTitle': 'सक्रिय उपयोगकर्ता प्रोफ़ाइल',
    'settings.role': 'कार्यकारी भूमिका',
    'settings.id': 'स्टेशन आईडी / बैज',
    'settings.status': 'सक्रिय सुरक्षित सत्र',
    'settings.languageTitle': 'भाषा प्राथमिकताएं',
    'settings.languageOverride': 'भाषा चयन (Language Override)',
    'settings.multiAgentView': 'मल्टी-एजंट व्यू मोड (Multi-Agent View)',
    'settings.lowBandwidth': 'लो-बैंडविड्थ मोड (Low-Bandwidth Mode)',
    'settings.standardView': 'मानक दृश्य',
    'settings.commandView': 'कमांड दृश्य',
    'settings.optionsTitle': 'सामान्य व अलर्ट विकल्प',
    'settings.audioAlerts': 'ऑडियो सायरन व ध्वनि अलर्ट',
    'settings.audioAlertsDesc': 'गंभीर घटनाओं का पता चलने पर उच्च-प्राथमिकता सायरन बजाएं',
    'settings.toastAlerts': 'स्क्रीन टोस्ट सूचनाएं (पॉप-अप)',
    'settings.toastAlertsDesc': 'भीड़ के जोखिम पर स्क्रीन पर रियल-टाइम सूचना कार्ड दिखाएं',
    'settings.vibration': 'हैप्टिक कंपन (वाइब्रेशन)',
    'settings.vibrationDesc': 'उच्च जोखिम वाले क्षेत्र में प्रवेश करने पर मोबाइल वाइब्रेट करें',
    'settings.offlineSync': 'ऑफलाइन मैप ऑटो-सिंक',
    'settings.offlineSyncDesc': 'बैकग्राउंड में रूट मैप और जल केंद्रों का डेटा स्वतः अपडेट करें',
    'settings.save': 'प्राथमिकताएं सहेजें',
    'settings.close': 'बंद करें',

    // Common Buttons & Badges
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.confirm': 'पुष्टि करें',
    'common.details': 'विवरण',
    'common.hide': 'छुपाएं',
    'common.active': 'सक्रिय',
    'common.resolved': 'हल हुआ',
    'common.critical': 'अति-गंभीर',
    'common.high': 'उच्च',
    'common.medium': 'मध्यम',
    'common.low': 'सामान्य',
    'common.syncCache': 'डेटा सिंक करें',
    'common.instantPilgrimAccess': 'सीधा वारकरी प्रवेश (लॉगिन की आवश्यकता नहीं)',
    'common.operationalStaff': 'अधिकारी / स्वयंसेवक लॉगिन',
  },
  
  mr: {
    // Brand & App
    'app.name': 'वारी-नेट (VARI-Net)',
    'app.subtitle': 'कमांड पोर्टल',
    'app.tagline': 'जोडा • अंदाज घ्या • सुचवा • सुरक्षित ठेवा',
    'app.location': 'पंढरपूर वारी',
    
    // Roles
    'role.police': 'पोलीस कमांड',
    'role.police.desc': 'घटना नियंत्रण, एआय हस्तक्षेप मंजुरी व जीआयएस कमांड',
    'role.volunteer': 'स्वयंसेवक फील्ड ऑप्स',
    'role.volunteer.desc': 'मैदानी कामे, गर्दी मार्गदर्शन व तत्काळ अहवाल',
    'role.pilgrim': 'वारकरी / भाविक ॲप',
    'role.pilgrim.desc': 'थेट सुरक्षित मार्ग, पाणी केंद्रे व आपत्कालीन एसओएस',
    'role.temple': 'मंदिर प्रशासन',
    'role.temple.desc': 'गाभारा दर्शन वेग, दर्शन रांग नियंत्रण व मंडप व्यवस्था',
    
    // Navigation & Header
    'nav.activeStation': 'सक्रिय स्थानक',
    'nav.unauthenticated': 'वारकरी सार्वजनिक प्रवेश',
    'nav.offline': 'ऑफलाईन (कॅश नकाशा)',
    'nav.lowNetwork': 'कमी नेटवर्क (कॅश सक्रिय)',
    'nav.online': 'थेट सिंक',
    'nav.liveClock': 'भारतीय वेळ',
    'nav.soundOn': 'ध्वनी अलर्ट चालू',
    'nav.soundOff': 'ध्वनी अलर्ट बंद',
    'nav.notifications': 'सूचना व अलर्ट्स',
    'nav.settings': 'सेटिंग्ज व प्रोफाईल',
    'nav.logout': 'लॉगआऊट व सत्र समाप्त',
    'nav.switchRole': 'भूमिका बदला',
    'nav.quickPilgrim': 'थेट वारकरी दर्शन',
    
    // Pilgrim App
    'pilgrim.emergencySos': '🚨 आपत्कालीन SOS',
    'pilgrim.safetyStatus': 'सद्य सुरक्षा स्थिती',
    'pilgrim.safeTitle': 'सेक्टर सी (पालखी मार्ग) सुरक्षित व मोकळा आहे',
    'pilgrim.safeDesc': 'गर्दीचा ओघ सुरळीत चालू आहे. वेग: ६४ वारकरी/मिनिट. १८० मीटर अंतरावर सावलीचा विश्राम मंडप उपलब्ध आहे.',
    'pilgrim.warningTitle': 'सावधान: पुढे शिवाजी चौकात गर्दीचा ताण वाढला आहे',
    'pilgrim.warningDesc': 'पालखी मार्गावर गर्दी अधिक आहे. एआय बायपास २ सावलीचा मार्ग वापरण्याचा सल्ला देत आहे.',
    'pilgrim.criticalTitle': 'अति-गंभीर इशारा: आपत्कालीन बायपास वापरा',
    'pilgrim.criticalDesc': 'मुख्य मार्गावर तीव्र गर्दी. कृपया उजवीकडे वळून बायपास २ सावलीच्या मार्गाने पुढे जा.',
    'pilgrim.nearestWater': 'जवळचे पिण्याचे पाणी केंद्र',
    'pilgrim.nearestMedical': 'जवळची वैद्यकीय मदत',
    'pilgrim.templeQueue': 'मंदिर दर्शन रांग',
    'pilgrim.waitTime': 'अपेक्षित वेळ',
    'pilgrim.minutes': 'मिनिटे',
    'pilgrim.meters': 'मीटर अंतरावर',
    'pilgrim.recommendedSafeRoute': 'एआय शिफारस केलेला सुरक्षित मार्ग (बायपास २)',
    'pilgrim.recommendedBadge': 'शिफारस • कमी गर्दी',
    'pilgrim.mainCorridor': 'मुख्य पालखी मार्ग (जास्त गर्दी)',
    'pilgrim.mapLayers': 'नकाशा लेअर्स',
    'pilgrim.routes': 'मार्ग',
    'pilgrim.facilities': 'सुविधा',
    'pilgrim.showAll': 'सर्व दाखवा',
    'pilgrim.walkingRoute': 'पायवाट पालखी मार्ग',
    'pilgrim.safeCorridor': 'एआय सुरक्षित कॉरिडॉर (बायपास २)',
    'pilgrim.waterPoints': 'पिण्याचे पाणी (पाणी केंद्रे)',
    'pilgrim.medicalCamps': 'वैद्यकीय व ICU छावणी',
    'pilgrim.toilets': 'शौचालये व स्वच्छता',
    'pilgrim.policeBooths': 'पोलीस व मदत केंद्र',
    'pilgrim.templeDarshan': 'मंदिर व दर्शन',
    'pilgrim.foodPrasad': 'महाप्रसाद व अन्नछत्र',
    'pilgrim.otherServices': 'इतर महत्त्वाच्या सेवा',
    'pilgrim.allServices': 'सर्व सेवा',
    'pilgrim.searchServices': 'जवळपासच्या सेवा शोधा...',
    'pilgrim.nearbyRadius': 'अंतर मर्यादा',
    'pilgrim.noServicesFound': 'कोणतीही नजीकची सेवा आढळली नाही',
    'pilgrim.noServicesFoundDesc': 'कृपया इतर प्रवर्ग निवडा किंवा शोध मर्यादा वाढवा.',
    'pilgrim.viewMore': 'अधिक पहा',
    'pilgrim.showLess': 'कमी करा',
    'pilgrim.resetFilters': 'फिल्टर रीसेट करा',
    'pilgrim.showingServices': 'दाखवत आहे',
    'pilgrim.shelters': 'विश्राम मंडप व अन्नछत्र',
    'pilgrim.riskZones': 'गर्दी सुरक्षा व धोका क्षेत्रे',

    // Temple Dashboard
    'temple.title': 'मंदिर गर्भगृह व दर्शन रांग नियंत्रण',
    'temple.activeZone': 'सक्रिय कार्य क्षेत्र',
    'temple.darshanQueue': 'दर्शन रांग',
    'temple.avgWait': 'सरासरी प्रतीक्षा वेळ',
    'temple.throughput': 'दर्शन प्रवाह दर',
    'temple.mandapCapacity': 'दर्शन मंडप क्षमता',
    'temple.mandapHeader': 'दर्शन मंडप प्रवाह व रांग नियंत्रण',
    'temple.sanctumPacing': 'गाभारा निकास व गती नियंत्रण',
    'temple.openReleaseGate': 'प्रवेश द्वार उघडा',
    'temple.pauseGate': 'रांग द्वार थांबवा',
    'temple.adjustPace': 'गती समायोजित करा',
    'temple.vipProtocol': 'व्हीआयपी प्रोटोकॉल',
    'temple.flowRate': 'निकास प्रवाह वेग',
    'temple.personsPerMin': 'वारकरी/मिनिट',
    'temple.queueLength': 'रांगेत एकूण वारकरी',
    'temple.holdingArea': 'मंडप क्षमता',
    'temple.gateStatus': 'गेट स्थिती',
    'temple.activeInterventions': 'सक्रिय व्यवस्था',
    'temple.emergencyBuffer': 'आपत्कालीन बफर क्षमता',

    // Police Dashboard
    'police.title': 'पोलीस कमांड व जलद प्रतिसाद केंद्र',
    'police.crowdTelemetry': 'ग्राउंड गर्दी टेलिमेट्री',
    'police.gisMap': 'थेट जीआयएस नकाशा',
    'police.incidentTriage': 'घटना निवारण व फील्ड पथके',
    'police.aiDecisionTitle': 'एआय पूर्वसूचना व निर्णय प्रणाली',
    'police.dispatchUnits': 'प्रतिसाद पथके रवाना करा',
    'police.activeIncidents': 'सक्रिय घटना',
    'police.resolvedIncidents': 'निवारण झालेल्या घटना',
    'police.totalIncidents': 'एकूण फील्ड अलर्ट्स',
    'police.density': 'गर्दी घनता',
    'police.surgeRisk': 'दाब धोका पातळी',
    'police.hotspots': 'सक्रिय संवेदनशील क्षेत्रे',
    'police.filterAll': 'सर्व प्राधान्ये',
    'police.filterCritical': 'फक्त अति-गंभीर',
    'police.filterHigh': 'उच्च प्राधान्य',
    'police.viewOnMap': 'नकाशावर पहा',
    'police.assignUnit': 'पथक नियुक्त करा',
    'police.markResolved': 'निवारण पूर्ण करा',

    // Volunteer Dashboard
    'volunteer.title': 'स्वयंसेवक फील्ड ऑप्स व कार्य व्यवस्था',
    'volunteer.quickReport': 'त्वरित मैदानी अहवाल (१० सेकंद)',
    'volunteer.assignedTasks': 'माझी नेमून दिलेली कामे',
    'volunteer.nearbyFacilities': 'जवळपासच्या मदत सुविधा',
    'volunteer.taskInProgress': 'चालू आहे',
    'volunteer.markComplete': 'पूर्ण झाले',
    'volunteer.acceptTask': 'काम स्वीकारा',
    'volunteer.activeVolunteers': 'सक्रिय स्वयंसेवक',
    'volunteer.completedTasks': 'पूर्ण झालेली कामे',
    'volunteer.distributeWater': 'पाणी व ओआरएस वाटप',
    'volunteer.waterPointsStatus': 'तपासलेली पाणी केंद्रे',
    'volunteer.medicalAssists': 'दिलेली वैद्यकीय मदत',
    'volunteer.activeZoneNotice': 'सक्रिय नेमून दिलेला भाग: सेक्टर सी (पालखी मार्ग)',

    // Decision Card
    'decision.title': 'एआय शिफारस केलेली गर्दी सुरक्षा कृती',
    'decision.confidence': 'एआय अचूकता',
    'decision.approve': 'मंजूर करा व मार्ग वळवा',
    'decision.approved': 'कारवाई मंजूर व सक्रिय',
    'decision.dismiss': 'शिफारस नाकारा',
    'decision.impactPreview': 'अपेक्षित टेलिमेट्री परिणाम',
    'decision.affectedZones': 'वळवण्याचे मुख्य मार्ग',
    'decision.corridors': 'मार्ग गर्दी घनता',
    'decision.timeline': 'वेळेत होणारी घट',
    'decision.beforeAfter': 'कारवाई आधी वि. नंतर',

    // Facility & Incidents
    'facility.capacity': 'क्षमता',
    'facility.route': 'मार्ग पहा',
    'facility.waterStation': 'पिण्याचे पाणी केंद्र',
    'facility.medicalCamp': 'वैद्यकीय केंद्र',
    'facility.policeBooth': 'पोलीस मदत कक्ष',
    'facility.sanitation': 'शौचालय गट',
    'facility.shelter': 'विश्राम शेड',
    'facility.prasadCamp': 'महा-प्रसाद केंद्र',
    
    'incident.acknowledge': 'नोंद घेतली',
    'incident.assign': 'पथक नियुक्त करा',
    'incident.resolve': 'निवारण पूर्ण करा',
    'incident.reportedBy': 'नोंदवणारे',
    'incident.photo': 'फोटो जोडला',
    'incident.voice': 'व्हॉइस नोट जोडली',
    
    // Weather & Microclimate
    'weather.title': 'स्थानिक हवामान रडार',
    'weather.temp': 'तापमान',
    'weather.humidity': 'आर्द्रता',
    'weather.wind': 'वाऱ्याचा वेग',
    'weather.heatRisk': 'उष्णतेचा धोका',
    'weather.dehydration': 'पाणी व ओआरएस सूचना',
    'weather.dehydrationDesc': 'या मार्गावर ओआरएस व भरपूर पाणी पिण्याची शिफारस आहे.',

    // Map Layers
    'map.layers': 'जीआयएस नकाशा लेअर्स',
    'map.quickFilter.title': 'जीआयएस जलद फिल्टर्स',
    'map.quickFilter.water': 'पाणी केंद्र',
    'map.quickFilter.medical': 'वैद्यकीय कक्ष',
    'map.quickFilter.police': 'पोलीस कक्ष',
    'map.quickFilter.food': 'अन्नछत्र',
    'map.quickFilter.safeCorridor': 'AI सुरक्षित मार्ग',
    'map.quickFilter.walkingRoutes': 'पालखी मुख्य मार्ग',
    'map.palkhiRoutes': 'पालखी मुख्य मार्ग',
    'map.altRoutes': 'पर्यायी कॉरिडॉर',
    'map.waterPoints': 'पिण्याचे पाणी व आरओ',
    'map.medicalCamps': 'वैद्यकीय केंद्र व रुग्णवाहिका',
    'map.policeBooths': 'पोलीस मदत कक्ष व पथक',
    'map.toilets': 'शौचालय ब्लॉक्स',
    'map.shelters': 'विश्राम शेड व अन्नछत्र',
    'map.parking': 'पार्किंग व बस स्थानक',
    'map.crowdDensity': 'थेट गर्दी घनता',
    'map.incidents': 'सक्रिय घटना',
    'map.volunteers': 'स्वयंसेवक पथके',
    'map.policeUnits': 'पोलीस गस्त पथक',
    'map.ambulances': 'रुग्णवाहिका पथके',
    'map.weatherOverlay': 'हवामान नकाशा',
    'map.riskZones': 'एआय धोका क्षेत्रे',
    'map.safeRoutes': 'एआय सुरक्षित कॉरिडॉर',
    'map.predictedCongestion': 'अपेक्षित गर्दी (१ तास)',
    'map.recommendedInterventions': 'हस्तक्षेप लक्ष्य क्षेत्रे',

    // Auth & Login
    'auth.welcome': 'वारी-नेट कमांडमध्ये आपले स्वागत आहे',
    'auth.heroDesc': 'पंढरपूर वारीसाठी एकात्मिक गर्दी सुरक्षा, स्थानिक हवामान टेलिमेट्री, थेट एआय मार्ग व्यवस्थापन आणि बहु-संस्था समन्वय.',
    'auth.fullName': 'पूर्ण नाव',
    'auth.userId': 'बॅज नंबर / अधिकारी आयडी',
    'auth.pin': 'पासवर्ड / सुरक्षा पिन',
    'auth.signIn': 'प्रवेश करा व कमांड सुरू करा',
    'auth.selectRole': 'कार्यकारी भूमिका निवडा',
    'auth.guestPilgrim': 'थेट वारकरी प्रवेश (लॉगिनची गरज नाही)',
    'auth.securityNotice': 'भूमिका आधारित सुरक्षा नियंत्रण • सुरक्षित सत्र',

    // Notifications & Stream
    'notif.title': 'कमांड अलर्ट स्ट्रीम',
    'notif.all': 'सर्व अलर्ट्स',
    'notif.critical': 'अति-गंभीर व महत्त्वाचे',
    'notif.ops': 'फील्ड ऑपरेशन्स',
    'notif.public': 'वारकरी व सार्वजनिक सूचना',
    'notif.empty': 'कोणताही सक्रिय अलर्ट नाही. सर्व व्यवस्था सुरळीत चालू आहे.',
    'notif.dismiss': 'काढून टाका',
    'notif.clearAll': 'सर्व साफ करा',
    'notif.viewAction': 'कारवाई पहा',
    'notif.toast': 'तात्काळ अलर्ट',

    // Expandable Action Bar Keys
    'actionBar.crowdDensityHeatmaps': 'गर्दी घनता हीटमॅप्स',
    'actionBar.activeInterventionsDiversions': 'सक्रिय हस्तक्षेप व वळण मार्ग',
    'actionBar.incidentTriageFieldUnits': 'घटना प्राधान्य व क्षेत्रीय पथके',
    'actionBar.alternateCorridors': 'पर्यायी कॉरिडॉर',
    'actionBar.interactiveGisMap': 'थेट GIS नकाशा',
    'actionBar.safeRouteNav': 'सुरक्षित मार्ग नेव्हिगेशन',
    'actionBar.nearbyServices': 'जवळपासच्या सुविधा (पाणी / स्वच्छता)',
    'actionBar.sectorWaitTimes': 'विविध सेक्टर प्रतीक्षा वेळ',
    'actionBar.emergencySos': 'आपत्कालीन SOS',
    'actionBar.queueControls': 'रांग व्यवस्थापन नियंत्रणे',
    'actionBar.darshanQueue': 'दर्शन रांग',
    'actionBar.assignedTasks': 'माझी नेमलेली कामे',
    'actionBar.facilities': 'सुविधा केंद्रे',
    'actionBar.quickIncidentReport': 'तात्काळ घटना अहवाल',
    
    // Settings & Profile Modal
    'settings.title': 'सार्वभौमिक प्रोफाईल व सेटिंग्ज',
    'settings.profileTitle': 'सक्रिय वापरकर्ता प्रोफाईल',
    'settings.role': 'कार्यकारी भूमिका',
    'settings.id': 'स्थानक आयडी / बॅज',
    'settings.status': 'सक्रिय सुरक्षित सत्र',
    'settings.languageTitle': 'भाषा प्राधान्ये',
    'settings.languageOverride': 'भाषा निवडा (Language Override)',
    'settings.multiAgentView': 'मल्टी-एजंट दृश्य मोड (Multi-Agent View)',
    'settings.lowBandwidth': 'लो-बँडविड्थ मोड (Low-Bandwidth Mode)',
    'settings.standardView': 'मानक दृश्य',
    'settings.commandView': 'कमांड दृश्य',
    'settings.optionsTitle': 'सामान्य व अलर्ट पर्याय',
    'settings.audioAlerts': 'ऑडिओ सायरन व ध्वनी सूचना',
    'settings.audioAlertsDesc': 'गंभीर घटना घडल्यास उच्च-प्राधान्य सायरन वाजवा',
    'settings.toastAlerts': 'स्क्रीन टोस्ट सूचना (पॉप-अप)',
    'settings.toastAlertsDesc': 'गर्दीच्या धोक्यावर स्क्रीनवर थेट तात्काळ सूचना कार्ड दाखवा',
    'settings.vibration': 'हॅप्टिक कंपन (व्हायब्रेशन अलर्ट)',
    'settings.vibrationDesc': 'जास्त गर्दीच्या किंवा संवेदनशील भागात प्रवेश केल्यास फोन व्हायब्रेट करा',
    'settings.offlineSync': 'ऑफलाईन नकाशा ऑटो-सिंक',
    'settings.offlineSyncDesc': 'बॅकग्राउंडमध्ये मार्ग व सुविधा केंद्रांचा डेटा आपोआप अपडेट करा',
    'settings.save': 'प्राधान्ये जतन करा',
    'settings.close': 'बंद करा',

    // Common Buttons & Badges
    'common.save': 'जतन करा',
    'common.cancel': 'रद्द करा',
    'common.confirm': 'पुष्टी करा',
    'common.details': 'तपशील',
    'common.hide': 'लपवा',
    'common.active': 'सक्रिय',
    'common.resolved': 'निवारण झाले',
    'common.critical': 'अति-गंभीर',
    'common.high': 'उच्च',
    'common.medium': 'मध्यम',
    'common.low': 'सामान्य',
    'common.syncCache': 'डेटा सिंक करा',
    'common.instantPilgrimAccess': 'थेट वारकरी प्रवेश (लॉगिनची गरज नाही)',
    'common.operationalStaff': 'अधिकारी / स्वयंसेवक लॉगिन',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY) as SupportedLanguage;
      if (saved === 'en' || saved === 'hi' || saved === 'mr') {
        return saved;
      }
    } catch {
      // Ignore
    }
    return 'en';
  });

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch {
      // Ignore
    }
  };

  const t = (key: string, defaultText?: string): string => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (dict[key]) return dict[key];
    if (TRANSLATIONS.en[key]) return TRANSLATIONS.en[key];
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
